### ISSUE TITLE
Plugin fails to start properly and outputs an error when using \g in a regex string

### ISSUE THREAD

**Issue by Zaichata** [anoyetta/ACT.SpecialSpellTimer#62]
Sorry I can't speak Japanese.

I am trying to create a ticker, I am inputting:

---
"Matching Log text to show:"
`:(?<name>[\w\' ]+) gains the effect of Suiton`

"Matching log text to hide:"
`\g<name>loses the effect of Suiton from`

"use regex" is ticked / allowed.

---
This works fine and as intended until ACT is restarted and then the plugin fails to start properly and outputs an error into its log:
```
[2017/02/24 01:43:32.824] An exception occurred in the Refresh of ACT.SpecialSpellTimer spell timer Window.
System.ArgumentException: parsing ".*\g<name>loses the effect of Suiton from.*" - Unrecognized escape sequence \g.
   at System.Text.RegularExpressions.RegexParser.ScanCharEscape()
   at System.Text.RegularExpressions.RegexParser.ScanBasicBackslash()
   at System.Text.RegularExpressions.RegexParser.ScanRegex()
   at System.Text.RegularExpressions.RegexParser.Parse(String re, RegexOptions op)
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, Boolean useCache)
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options)
   at ACT.SpecialSpellTimer.Utility.StringExtensions.ToRegex(String s)
   at ACT.SpecialSpellTimer.OnePointTelopTable.get_EnabledTableCore()
   at ACT.SpecialSpellTimer.OnePointTelopTable.get_EnabledTable()
   at ACT.SpecialSpellTimer.SpellTimerCore.RefreshWindowTimerOnTick(Object sender, EventArgs e)
```

Removing the strings that contain \g, saving, putting the strings back in and saving again works as a short term fix but it will fail to start again and output errors upon a subsequent ACT restart.

**Comment by anoyetta** [comment]
"g" must be capitalized.
"\G" is correct?

**Comment by ProfX66** [comment]
I think he is trying to find something with "\g" in it so technically that should be "\\g". Can you try that @Zaichata ?

That error looks like it points more toward string representation in .net. Meaning if you were to do "Foo\Bar" with out either escaping the slash or adding an @ directive to the front of the string you would receive the exact same error as what the exception message is stating.

**Comment by Zaichata** [comment]
\G seems to get rid of the errors but it stops the string from doing its purpose.

What i want to be able to do is, for example, store the name of a character into a variable type thing and give it the name "name"
To that end \g<name> should refer back to the name of the character adding it to the second string to search for.

For example:

---
if the name of a character performing suiton was "Zai ch'ata" then:


`:(?<name>[\w\' ]+) gains the effect of Suiton` 
would find 
"Zai ch'ata gains the effect of Suiton"
and start the timer.

`\g<name>loses the effect of Suiton from`
would then search for
"Zai ch'ata loses the effect of Suiton from"
and end the timer when found.

**Comment by ProfX66** [comment]
So it looks like hes trying to use a backreference (\g is that in Python), I believe that \k is that in .net.

@Zaichata can you try and change the "\g" to "\k" and see if you get the same startup error?

**Comment by Zaichata** [comment]
the startup error still occurs. Same output.

**Comment by Zaichata** [comment]
On further investigation i'm getting the feeling both \g and \k do not work as intended at all, as when they are inserted into the string the plugin seems to actually use the last saved successful configuration and does not override the active regex string with anything. I think this may be what is causing my confusion.

Though it still may be worth looking into? as \g or \k would still be helpful in differentiating specific strings.

**Comment by Blade2187** [comment]
This is more or less a duplicate of issue #56. At the time I did a cursory inspection of the code and it seemed it would be pretty involved to actually get that working as it uses two entirely separate regex queries for this.
