### ISSUE TITLE
plugin will not load; crashes ACT

### ISSUE THREAD

**Issue by tippani** [anoyetta/ACT.SpecialSpellTimer#74]
does anyone have insight on why I am unable to load the plugin? it will crash my ACT if i try to load it.

**Comment by anoyetta** [comment]
I can not tell by just this information. 
However, is not .NET Framework 4.7 installed?

https://www.microsoft.com/en-us/download/details.aspx?id=55170

**Comment by tippani** [comment]
.NET Framework 4.7 is installed. It was working fine for me until about May 2017. Many updates have been pushed since then and none have seemed to resolve my issue, unfortunately. is there an error log I can try and find?

**Comment by anoyetta** [comment]
%APPDATA%\Advanced Combat Tracker\Advanced Combat Tracker.log
%APPDATA%\anoyetta\ACT\ACT.SpecialSpellTimer.*.log
The log is here. Please send it to me.

**Comment by tippani** [comment]
[Advanced Combat Tracker.zip](https://github.com/anoyetta/ACT.SpecialSpellTimer/files/1181558/Advanced.Combat.Tracker.zip)

**Comment by tippani** [comment]
[ACT.SpecialSpellTimer.2017-04.zip](https://github.com/anoyetta/ACT.SpecialSpellTimer/files/1181562/ACT.SpecialSpellTimer.2017-04.zip)
this is the only spelltimer log i found that had some errors show up

**Comment by anoyetta** [comment]
ACT.SpecialSpellTimer.2017-04.zip

This log is old. It's April.
Please send the log of July.
You ought to have a log of July. ACT.SpecialSpellTimer.2017-07.log

**Comment by tippani** [comment]
[ACT.SpecialSpellTimer.2017-07.zip](https://github.com/anoyetta/ACT.SpecialSpellTimer/files/1181587/ACT.SpecialSpellTimer.2017-07.zip)

ACT does not crash until I launch FFXIV, even with specialspelltimers enabled.  if FFXIV is already loaded and I turn on ACT, it will crash if specialspelltimers is enabled.

**Comment by anoyetta** [comment]
I'm sorry but I do not know anything.

There is nothing in the log showing any error.
There is an error in the April log, but it seems unrelated to this case.
In my environment the error has not been reproduced.

I can not do anything because I can not find the cause.

**Comment by xDemonessx** [comment]
I'm experiencing the same issue:

************** Exception Text **************
System.TypeLoadException: Could not load type 'System.ValueTuple`3' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at ACT.SpecialSpellTimer.ConfigPanel.UpdatePlaceholder()
   at ACT.SpecialSpellTimer.ConfigPanel.LoadLogTab()
   at System.Windows.Forms.UserControl.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.OnVisibleChanged(EventArgs e)
   at System.Windows.Forms.Control.OnParentVisibleChanged(EventArgs e)
   at System.Windows.Forms.Control.OnVisibleChanged(EventArgs e)
   at System.Windows.Forms.Control.SetVisibleCore(Boolean value)
   at System.Windows.Forms.TabPage.set_Visible(Boolean value)
   at System.Windows.Forms.TabControl.UpdateTabSelection(Boolean updateFocus)
   at System.Windows.Forms.TabControl.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.TabControl.WmSelChange()
   at System.Windows.Forms.TabControl.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Advanced Combat Tracker
    Assembly Version: 3.3.1.255
    Win32 Version: 3.3.1.255
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Advanced%20Combat%20Tracker.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
GammaJul.LgLcd
    Assembly Version: 1.1.3.0
    Win32 Version: 1.1.3.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/GammaJul.LgLcd.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
ICSharpCode.SharpZipLib
    Assembly Version: 0.85.5.452
    Win32 Version: 0.85.5.452
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/ICSharpCode.SharpZipLib.DLL
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
FFXIV_ACT_Plugin
    Assembly Version: 1.5.1.5
    Win32 Version: 3.3.1.255
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Advanced%20Combat%20Tracker.exe
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
OverlayPlugin
    Assembly Version: 0.3.3.11
    Win32 Version: 3.3.1.255
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Advanced%20Combat%20Tracker.exe
----------------------------------------
OverlayPlugin.Common
    Assembly Version: 0.3.3.11
    Win32 Version: 0.3.3.11
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin0.3.3.11/OverlayPlugin.Common.dll
----------------------------------------
OverlayPlugin.Core
    Assembly Version: 0.3.3.11
    Win32 Version: 0.3.3.11
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin0.3.3.11/OverlayPlugin.Core.dll
----------------------------------------
HtmlRenderer
    Assembly Version: 1.0.1.6
    Win32 Version: 1.0.1.6
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin0.3.3.11/HtmlRenderer.dll
----------------------------------------
Xilium.CefGlue
    Assembly Version: 3.2272.2035.0
    Win32 Version: 3.2272.2035.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin0.3.3.11/Xilium.CefGlue.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
ACT.SpecialSpellTimer
    Assembly Version: 1.20.0.4
    Win32 Version: 3.3.1.255
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Advanced%20Combat%20Tracker.exe
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
System.Data.DataSetExtensions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Data.DataSetExtensions/v4.0_4.0.0.0__b77a5c561934e089/System.Data.DataSetExtensions.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------
ACT.SpecialSpellTimer
    Assembly Version: 1.20.0.4
    Win32 Version: 3.3.1.255
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Advanced%20Combat%20Tracker.exe
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
ACT.SpecialSpellTimer
    Assembly Version: 1.20.0.4
    Win32 Version: 3.3.1.255
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Advanced%20Combat%20Tracker.exe
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
ACT.SpecialSpellTimer
    Assembly Version: 1.20.0.4
    Win32 Version: 3.3.1.255
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Advanced%20Combat%20Tracker.exe
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by anoyetta** [comment]
to xDemonessx

That's because the .NET Framework is out of date.
Tuple is a function since 4.7, so .NET Framework 4.7 is required.

**Comment by xDemonessx** [comment]
Thanks, can confirm 4.7 framework was the cause.
